### ISSUE TITLE
OpenCopilot can't answer any questions about the API

### ISSUE THREAD

**Issue by ronaldlong46** [openchatai/OpenCopilot#105]
[**Describe] the bug**
OpenCopilot can't answer any questions about the API. When I submitted my swagger.json there were no validation issues.

**Expected behavior**
Copilot to have knowledge of the API.

**Screenshots**
![Screenshot 2023-09-27 at 1 31 47 PM](https://github.com/openchatai/OpenCopilot/assets/35465493/b7d5ef22-0a2c-45c2-b10c-2b3bf44a8081)

**Comment by codebanesr** [comment]
@ronaldlong46 would it be possible for you to share your swagger file with us ?

**Comment by codebanesr** [comment]
Hey @ronaldlong46, 
I've just discovered that the issue you're encountering, where the bot responds with the same text as the prompt, is due to agents struggling to interpret the output from LLM. This problem has also been reported by other users of Langchain agents, as mentioned in this GitHub discussion: https://github.com/langchain-ai/langchain/discussions/4065. It appears that setting the model to its default value, davinci, significantly reduces this error. I've already implemented these changes, and we'll be rolling out a fix shortly. Additionally, we may require a sample swagger file to investigate further if there are any additional issues involved.
