### ISSUE TITLE
Can't import a Swagger file

### ISSUE THREAD

**Issue by alexiri** [openchatai/OpenCopilot#482]
**Describe the bug**
Importing a swagger file while creating a copilot fails with no error. The copilot is left with no APIs, they can't be edited after the fact (#47) and it also can't be deleted  (#447).

**To Reproduce**
1. Go to [the main page](https://cloud.opencopilot.so/)
2. Click on 'Create Copilot'
3. Give it a name in step 2 of the wizard
4. In step 3, import [the swagger file](https://petstore.swagger.io/v2/swagger.json) from https://petstore.swagger.io/
5. Watch how nothing happens.

**Expected behavior**
The swagger file should be imported.

**Screenshots**
The console shows the following errors:

![image](https://github.com/openchatai/OpenCopilot/assets/5055697/eb05488d-4766-4d28-834b-a2fe2ab3487d)

The response from that 404 request is the following:

```
{"is_error":true,"message":"Failed to parse Swagger file: No servers found in Swagger data."}
```

The swagger file does have a server specified, though:

```
"host":"petstore.swagger.io"
```

Here I *am* assuming that the swagger file from swagger.io is in fact correctly formed, but given that they're the standardizing body, I think it's a fair assumption.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 121.0

**Comment by gharbat** [comment]
Hi @alexiri thanks for raising this!

The parser only supports OpenAPI 3.0 which relies on `servers` to get the base URL, I think `hosts` is used in OpenAPI 2.0.

I will ship a change to make it more apparent in the error message, in the meanwhile maybe you can take a look here https://github.com/openchatai/OpenCopilot/blob/main/llm-server/utils/swagger_parser.py#L150 , I think if we added another check for `hosts` it will work! because the rest is the same between 3.0 and 2.0.

-----

For the delete part, I will take a look at it today.

**Comment by codebanesr** [comment]
Also, @alexiri when you download the swagger file from petstore, it doesn't have the full server url. Please set it up like this 

<img width="712" alt="Screenshot 2024-01-06 at 3 32 39 PM" src="https://github.com/openchatai/OpenCopilot/assets/17947802/a4175ff8-e971-4de1-8744-66b76afeef2f">

**Comment by codebanesr** [comment]
@ah7255703 The error is not being displayed on the frontend when swagger parsing fails
